### ISSUE TITLE
Add bin symlink for CLI?

### ISSUE THREAD

**Issue by danyalaytekin** [paulirish/third-party-decode#2]
It would be nice to have this available as a shell command, without setting up an alias.

e.g.

```
npm install -g third-party-decode
decode3p "http://cdn.krxd.net"
```

**Comment by paulirish** [comment]
works for me. wanna give me a pull request?  afaik it's as straightforward as the package.json edit

**Comment by danyalaytekin** [comment]
Sure, will have a look shortly, hopefully 😄 .

**Comment by danyalaytekin** [comment]
Sorry Paul.  Hope you're well.

**Comment by paulirish** [comment]
all good dude.  peace!
