### ISSUE TITLE
Suggestion: Web interface and a JSON endpoint

### ISSUE THREAD

**Issue by mauryaratan** [paulirish/third-party-decode#3]
Hey Paul,
I quickly put together a website at https://third-party-decode.glitch.me/ for one of an internal need to grab the badge.

Which also happen to accept a request as https://third-party-decode.glitch.me/badge?url=https://cdn.krxd.net and returns the following format:

```js
{
  "name": "Krux Digital, Inc.",
  "type": "analytics",
  "badge": "KD"
}
```
If you think it can be handy for others, I can submit a pull request with included instructions in readme file. Let me know your thoughts 👍

**Comment by paulirish** [comment]
Very cool. Looks great!
